name: root
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
    - mlgill
    - gilbertfrancois
    - bioconda
    - jim-hart
    - soumith
    - intel
    - pytorch
    - mcs07
    - pjmtdw
dependencies:
    - python=3.6
#    - nomkl
    - numpy=1.15.*
#    - matplotlib=2.1.*
#    - bokeh=0.12.*
    - opencv=3.4.*
#    - dlib=19.4
#    - pillow=5.0.*
    - scikit-learn=0.19.*
    - scikit-image=0.14.*
    - scipy=1.1.*
#    - h5py=2.7.*
    - eventlet=0.22.*
    - flask-socketio=2.9.*
#    - seaborn=0.8.*
#    - pandas=0.22.*
    - imageio=2.4.*
#    - pyqt=5.6.*
    - xgboost=0.72.*
    - leptonica=1.76
#    - pytorch=0.4.*
#    - torchvision=0.2.*
#    - sympy=1.1.*
    - gensim=3.3.*
    - spacy=2.0.*
    - tesseract=4.0.*
    - moviepy=0.2.*
#    - protobuf=3.5.*
#    - mxnet-cudnn=1.2.*
#    - mxnet=1.2.*
    - ffmpeg=4.0.*
    - imutils=0.4.*
    - pysoundfile=0.10.*
    - fire=0.1.*
    - psutil=5.4.*
    - plotly=3.4.*
    - shapely=1.6.*
    - boto3=1.9.*
    - tqdm=4.29.*
    - pip:
        - kaggle
        - slidingwindow==0.0.13
        - git+https://github.com/tensorpack/tensorpack
        - librosa==0.6.*
        - https://pypi.python.org/packages/c5/9e/42d7bcddb09a3ff52d0c60c810ba5d0fded28abbe320c85bbf7368192956/sklearn_pandas-1.6.0-py2.py3-none-any.whl
        - git+https://github.com/aleju/imgaug
        - https://github.com/evdcush/TensorFlow-wheels/releases/download/tf-1.12.0-gpu-10.0/tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl
#        - https://github.com/evdcush/TensorFlow-wheels/releases/download/tf-1.11.0-gpu-10.0_7.3_5.0-mkl/tensorflow-1.11.0-cp36-cp36m-linux_x86_64.whl
#        - https://github.com/evdcush/TensorFlow-wheels/releases/download/tf-1.10.0-gpu-9.2-tensorrt-mkl/tensorflow-1.10.0-cp36-cp36m-linux_x86_64.whl
#        - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.10.1-cp36-cp36m-linux_x86_64.whl
        - keras==2.2.4
        - edward==1.3.5
        - catboost==0.6.1.1
        - jupyter-tensorboard
        - git+https://www.github.com/ildoonet/tf-openpose
        - tesserocr==2.4.*

